---
deployment:
  tasks:
    # Target folder aplikasi aktif SIKAP di cPanel
    - export DEPLOYPATH=/home/slnawang/sikap-app/
    
    # Sinkronisasi file dari repositori ke direktori aplikasi
    # Mengecualikan .git, .env, dan direktori storage agar data upload & konfigurasi aman
    - /bin/rsync -av --exclude='.git' --exclude='.env' --exclude='storage' ./ $DEPLOYPATH
