---
deployment:
  tasks:
    # Target folder aplikasi aktif SIKAP di cPanel
    - export DEPLOYPATH=/home/sinawang/sikap-app/
    
    # Sinkronisasi file dari repositori ke direktori aplikasi
    # Mengecualikan .git, .cpanel.yml, .env, dan storage agar aman
    - /bin/rsync -aP --exclude='.git' --exclude='.cpanel.yml' --exclude='.env' --exclude='storage' ./ $DEPLOYPATH
